### PR TITLE
Some cleanups for input on (not necessarily for merging)

### PR DESCRIPTION
**Pull request by vodik**
I thought I'd put this up as a merge request mainly for the peer review, I'm not really expecting this to get merged as is, though probably safe to do so.

#145 is the last merge request that I'd consider sufficient to land for issue #109 to be closed. So going forward I want to start putting effort into cleaning up the code base. This change set, thus far:

1. Cleans up `actions.cpp` code to line up with the set standard.
2. Removes some dead functions and types - stuff that's not used anywhere.
3. Removes trivial getters and setters. There's no point, the member could just be exposed publicly.
4. Defines a copy and move constructor for `CAction` (afaik, the default implementations are fine).
5. Removes `CActions` completely and replaces it with a `vector`.

And a few other misc changes. Dropping `CActions` for a vector might improve cache locality and thus performance, but I don't have any benchmarks to back that up.

If you guys are amicable to this kind of work, I plan to keep it coming. But I'm bringing it up to get feedback and an idea of how comfortable you guys are with these kinds of changes.

### CODE REVIEW

**Comment by vodik** [comment]
Also what are your guys' opinions on the prefixing? eg `CAction`, `T_IntCmdType`, `M_scenario`, which are inconsistently done only in parts of the code base and imho don't add anything of value to the names.

**Comment by wdoekes** [comment]
> Also what are your guys' opinions on the prefixing?

The only prefix I find somewhat useful is an `m_` prefix for member attributes. (Particularly in this codebase where many globals are used as well; "is this a local, member or global var?") But I can certainly live without them.

**Comment by vodik** [comment]
I just realized this is growing quite large, I'll stop pushing dev work to this branch.

**Comment by wdoekes** [comment]
Awesome cleanup work!

Code changes look good. Compiles (after removing noexcept). Regression tests run.

And I like this bit a lot:
```
$ git diff | wdiffcount 
1367 - 1792 = -425
```

**Comment by vodik** [comment]
Yeah and a lot less manual memory management. I think I've addressed everything.

**Comment by vodik** [comment]
Okay, so  this was prematurely merged, I'm going to the mature thing and yank it. Sorry, it should have been more extensively tested and I'm not confident I've fixed everything with the next damage control merge.

I'll polish this one up more in private before posting it again. Sorry again.

**Pull request merged**
