### PR TITLE
Gateway RTP/SRTP bit pattern testing support (SIPP-RTPCHECK-3.6)

### PR DESCRIPTION
**Pull request by jeannotlanglois**
[Detailed feature documentation available upon request]
NOTE:  Requires --with-rtpstream --with-openssl

### CODE REVIEW

**Comment by wdoekes** [comment]
Hi!

Thanks for the PR.

Can you take care of the travis build failures?

**Comment by jeannotlanglois** [comment]
Hi Walter,

I can probably take care of them -- but it will take a while as I can't promise my availability nowadays...  I have a very busy time in the office here.  So as long as you don't mind waiting for some time (probably a few weeks at the rate that things are going for me here unfortunately).

As long as there's not too much activity on the SIPp stream it shouldn't be too hard to rebase if I wait a while.

--
Jeannot Langlois
Software Developer
MiVoice Border Gateway Development
Mitel Networks
350 Legget Drive, Kanata, Ontario K2K 2W7
http://www.mitel.com<http://www.mitel.com/>

“
It’s not over until I win.
“
-- Leslie Brown

**Comment by orgads** [comment]
Hi,

I rebased it for you. Checkout https://github.com/orgads/sipp/commits/srtp

I also fixed build on Windows, and against openssl 1.1.

The changelog entry that you removed looks irrelevant, as 3.6 was already released, so this is for 3.7. You may add a new entry for 3.7.

There are many warnings on Windows regarding conversion of pthread_t to int (mostly on printf's). I worked around those who are considered errors (when passing pthread_t to a function that expects int), by casting to long long and then to int, but you should consider really fixing it..

**Comment by jeannotlanglois** [comment]
Thanks Shaneh:

I'm away from my workplace for several months as I'm recovering from multiple injuries.  Therefore your help is really appreciated.

Unfortunately I might have to wait until later this year to resume my work on SIPP-RTPCHECK.  I'm just barely in the slow process of attempting a return to work this month.

I had a good look at the rebased diff, at first glance, things look good.
I do not have my GitHub credentials here at home so I can't leave comments yet.  But I will try to do eventually.

Thanks for the help again! :)


--
Jeannot Langlois
Software Developer
MiVoice Border Gateway Development
Mitel Networks
350 Legget Drive, Kanata, Ontario K2K 2W7
http://www.mitel.com<http://www.mitel.com/>
Jeannot.langlois@mitel.com<mailto:Jeannot.langlois@mitel.com>
(613) 592-5660 x74420
(613) 691-3385 [Direct Dial]

“
It’s not over until I win.
“
-- Leslie Brown

**Comment by rkday** [comment]
Closing this, as the discussion is continuing on #417.

**Pull request closed without merging**
