### PR TITLE
Snom patch: header value syntax

### PR DESCRIPTION
**Pull request by pbertera**
**Last header value:** you can extract the header value using the *!* suffix to the `[last_headerName]`

**Example:**
`To: [last_From!]`

will generates a *To:* header containing the last From header value, this is quite useful when you need to send a new request (Eg. re-INVITE into an inbound SIP dialog)

Of course you can do the same using a regexp, but this syntax simplifies a lot the scenario file.

*All the attribution for this patch should go to Snom Technology AG*

### CODE REVIEW

**Comment by wdoekes** [comment]
Thanks for the patch with testcase.

Could you make that into `[last_From.value]` instead, as suggested in #132 ? The code changes you provided aren't as clean as they could be, but I'll wait with reviewing.

And, this lack all documentation, visible and invisible. A possible way to document its existence could be to add it to one of the built-in scenario's...

(Lastly, your commits aren't atomic changes. They'll need to be squashed before I could merge. And the testcase naming should either be `github-#XXXX` (reference to ticker XXXX on github) or some discriptive name, like `last_header_value` in which case the "github" makes no sense.)

**Comment by pbertera** [comment]
Thanks for the feedback,
- about the naming: I agree that using the `value`keyword will make the syntax more clear, I would like to have an opinion about using `:` as a separator (see #132).
- about the documentation: what about to add a new scenario (uas-req.xml) where the BYE comes from the uas ?

**Comment by wdoekes** [comment]
> I would like to have an opinion about using `:` as a separator

Sounds good to me. (And it provides more legitimacy for the `:` being optional like it is right now.)

> What about to add a new scenario (uas-req.xml) where the BYE comes from the uas?

I'm a bit reluctant to add new scenario's into the binary itself. If you add it to a samples directory as separate xml file, it would work for me. (Especially if a test case runs it, so the scenario's do not get stale.)

**Comment by wdoekes** [comment]
Closes in favor of WIP in #260.

**Pull request closed without merging**
