### PR TITLE
Added -noscreen option to disable status and result screen.

### PR DESCRIPTION
**Pull request by kovacsbalu**

### CODE REVIEW

**Comment by vodik** [comment]
Yeah, if we want an explicit flag, this should be redone ontop of #130 because this also disables signal handling.

**Comment by wdoekes** [comment]
Thanks for the initial pull request though. It's appreciated!

I think we can do without a command line option though, right?

**Comment by wdoekes** [comment]
(fed347b was superseded by c2381c8 -- fixed log message)

**Comment by kovacsbalu** [comment]
Yep, I'll check it! :)

**Pull request closed without merging**
