### PR TITLE
SRTP: Replace AES ECB with AES CBC

### PR DESCRIPTION
**Pull request by orgads**
ECB is not built on alpine wolfssl.

### CODE REVIEW

**Comment by orgads** [comment]
@jeannotlanglois Can you suggest what to do here? This breaks the srtp test.

**Comment by orgads** [comment]
It also fails in #738.

**Comment by jeannotlanglois** [comment]
As per SIP RFCs 3711 and 4568, ECB is needed in order to use the counter mode (CTR) which is *required* by the SRTP protocol.
As far as my understanding goes, this cannot be changed as the protocol is based on that AES behavior.  This is why the SRTP tests fail.

**Comment by orgads** [comment]
Thank you @jeannotlanglois. I'll see what I can do.

**Comment by orgads** [comment]
Superseded by #759.

**Pull request closed without merging**
