### PR TITLE
Add media support for comfort noise (audio/CN)

### PR DESCRIPTION
**Pull request by rsvargas**
Make it possible to playback a PCAP file or echo received streams containing CN packets.

### CODE REVIEW

**Comment by rsvargas** [comment]
This will also fix #632.

**Comment by lemenkov** [comment]
Looks good to me. Passes all the tests. One question - have you tested it?

**Comment by rsvargas** [comment]
I did tested it, but it was some time ago, I've had this commit in my local copy for a while, so when I saw it recently I rebased my branch and made the PR.

**Comment by lemenkov** [comment]
OK, let's merge it.

**Pull request merged**
