### PR TITLE
Enable SiPp to use TLS1.2

### PR DESCRIPTION
**Pull request by arunrajm**

### CODE REVIEW

**Comment by orgads** [comment]
:+1:

**Comment by orgads** [comment]
Any reason not to accept this?

**Comment by wdoekes** [comment]
The only reason would be backwards compatibility. But it does pass the tests, so that's good.

In short: it's probably going in.

**Comment by wdoekes** [comment]
> TLS_method(), TLS_server_method(), TLS_client_method()
> These are the general-purpose version-flexible SSL/TLS methods. The actual protocol version used will be negotiated to the highest version mutually supported by the client and the server. The supported protocols are TLSv1, TLSv1.1 and TLSv1.2. Applications should use these methods and avoid the version-specific methods described below.

I'm guessing those should be appropriate instead. (Note that we're not going for best-encryption here, but for compatible with the most devices.)

**Comment by wdoekes** [comment]
That would be something for autoconf then.

**Comment by orgads** [comment]
Proposed a new patch: https://github.com/SIPp/sipp/pull/341

**Comment by wdoekes** [comment]
Fixed by 553290318. Thanks!

**Pull request closed without merging**
