### PR TITLE
Get rid of "using namespace std" everywhere

### PR DESCRIPTION
**Pull request by orgads**
Use consistent scoping.

### CODE REVIEW

**Comment by orgads** [comment]
@wdoekes The failures here are unrelated to my changes. Can you please approve it?

**Comment by wdoekes** [comment]
No sneaky ifunc additions here, right? ;P

**Comment by orgads** [comment]
🤣🤣

**Comment by wdoekes** [comment]
There are some other changes than just adding std:: (adding auto, replacing heap with stack alloc), but I guess it's fine. We did auto already, I see. And the stack is only for the better here.

**Review by wdoekes — APPROVED** [review]

**Comment by orgads** [comment]
I preferred changing to auto rather than `std::map<whatever>::iterator`...

**Pull request merged**
