### PR TITLE
Improve SDP parsing to accept \n as line terminator

### PR DESCRIPTION
**Pull request by vodik**
RFC 4566 says parers SHOULD accept both single CR and LF characters as line terminators:

> The sequence CRLF (0x0d0a) is used to end a record, although parsers SHOULD be tolerant and also accept records terminated with a single newline character.

### CODE REVIEW

**Comment by rkday** [comment]
Looks fine to me. I prefer `char* x` to `char *x`, though - the file's already inconsistent between the two, but we should standardise on one rather than staying inconsistent.

**Comment by vodik** [comment]
For what its worth, I prefer `char *x` to `char* x` because the `*` is bound to the variable, not the type. I always thought the alternative style is a mistake. After all: its: 

~~~c
char *foo = NULL, *bar = NULL;
~~~

though whether or not you think defining multiple variables on one line is a good thing or not is another style issue that can be debated.

Anyways, now that I've stated my preference, don't think I'm willing to change since I'm not the one doing the maintenance.

**Comment by wdoekes** [comment]
> don't think I'm willing

I assume you meant "don't think I'm not willing" ;)

Anyways, I've automated the use of your style too (`char *x`), until I do a cast at which point the extra space distracts (`(char *)x`). If I look in the C header files, I see `char *x` everywhere, but if I look in the C++ headers (`/usr/include/c++/4.8/istream`) I see `char* x`. That happens to be Bjarne's stand:
http://www.stroustrup.com/bs_faq2.html#whitespace

> A "typical C++ programmer" writes `int* p;` and explains it "p is a pointer to an int" emphasizing 
type. Indeed the type of `p` is `int*`. I clearly prefer that emphasis and see it as important for using the more advanced parts of C++ well.

So, I'll agree with Rob that we should move to `char* x` for new code.

**Comment by vodik** [comment]
Two against one, oh well...

> I assume you meant "don't think I'm not willing" ;)

Gah, yeah, that's what I meant. I'll fix this up when I got some time later today.

**Comment by vodik** [comment]
Alright, updated.

**Comment by wdoekes** [comment]
Thanks!

**Pull request merged**
