### PR TITLE
Ethernet 802.1Q tagged frames processing.

### PR DESCRIPTION
**Pull request by hpaskalev**
Currently SIPp doesn't handle 802.1Q tagged frames. This patch provides handling of such frames and correct Ethernet type extraction.

### CODE REVIEW

**Comment by vodik** [comment]
Hey, so looks good, just one things so we can merge it.

Have a [style guide](https://github.com/SIPp/sipp#contributing), if you could get this code to conform to it, it be awesome (mainly looking at your conditionals). And unless someone else is going to overrule me, I'm also not a fan of the `0x0800 != eth_type` style of comparison. I understand why people code like that, but it reads nicer, imho, the other way.

**Comment by hpaskalev** [comment]
I don't mind pushing another reformat. :)

**Comment by vodik** [comment]
It probably be a good idea to squash all your commits down to a single commit. I'll leave it someone else to review further.

**Comment by hpaskalev** [comment]
Sure, it's a good idea.

**Pull request merged**
