### PR TITLE
Gateway RTP/SRTP bit pattern testing extra fixes/documentation

### PR DESCRIPTION
**Pull request by jeannotlanglois**
@wdoekes + @rkday  : 

As promised back in late August 2020 here are the few missing parts to complete my submission of the RTPCHECK functionality for SIPP 3.7 -- all remaining points have been addressed:

>The changelog entry that you removed looks irrelevant, as 3.6 was already released, so this is for 3.7. You may add a new entry >for 3.7.

(Jeannot) CHANGES.md updated to reflect the new RTPCHECK functionality for SIPP 3.7.

>There are many warnings on Windows regarding conversion of pthread_t to int (mostly on printf's). I worked around those who >are considered errors (when passing pthread_t to a function that expects int), by casting to long long and then to int, but you >should consider really fixing it..

(Jeannot) CygWin build fixed+tested with CygWin 3.1.4(0.340/5/3).  Turns out that the CygWin implementation of pthread_t only has a dummy integer for thread ids (luckily RTPCHECK only uses this in a handful of places for debugging so I have stubbed it to -1) -- no more warnings/errors.

Also: 
1) Linux build reverified.
2) Darwin build reverified.

ALL runtime tests re-run.

>"SET-SIDE" + "ICP-SIDE" mentioned in command line examples.

(Jeannot) SET-SIDE replaced by "UAC" to align with official term.
(Jeannot) ICP-SIDE replaced by "UAS" to align with official term.

>I have the full documentation available in a PDF document (exported from an internal Confluence page) with a few illustrations >showing the signalling/streaming flow directions, as well as examples of every possible syntax. Maybe an ASCII version might >need to be drafted however if PDF is not adequate. 

(Jeannot) PDF documentation updated + submitted as rtpcheck_xml_syntax_reference.pdf for FULL details on how to use the RTPCHECK functionality.

> I don't believe that I've tested "-mp" and "-max_rtp_port" interactions.

Verified that both "-min_rtp_port" + "-max_rtp_port" parameters had indeed been unnecessarily brought back during my rebases to SIPP-3.6 so I have ensured that they have been removed for good now.

1) Linux build reverified.
2) Darwin build reverified.
3) CygWin build reverified.

ALL runtime tests re-run.

This completes all the items I had on my list for now.
If I can find more free time before the end of this year I think the next logical move would be to proceed with a refactoring of some of the RTPCHECK code which is a bit repetitive in some areas and is lacking some code documentation.  But that would be a separate submission when time allows.

Hopefully this should now allow proper release of SIPP 3.7.
Cheers...

### CODE REVIEW

**Comment by jeannotlanglois** [comment]
Hi @wdoekes , @rkday :  

As promised I have completed the few last remaining bits of the work requested for Gateway SRTP/RTP bit pattern testing.  The current submission should hopefully address all the remaining concerns.

Could the RTPCHECK submission be enough to warrant a new SIPP 3.7 release?  
Thanks!

**Comment by wdoekes** [comment]
Awesome!

> Could the RTPCHECK submission be enough to warrant a new SIPP 3.7 release?

Yes. Now I just have to find some time to review and merge (and release) :)

Do remind me in case I forget.

**Comment by jeannotlanglois** [comment]
@wdoekes , @rkday :  Ok -- I will check back again in december.  Looking forward to announce this to coworkers who will likely use it to test it further.  Thanks!

**Comment by jeannotlanglois** [comment]
Hello @wdoekes, @rkday : 

`Yes. Now I just have to find some time to review and merge (and release) :)
Do remind me in case I forget.`

This is just a reminder to merge this pull request -- and likely proceed with the SIPP-3.7 release.
Cheers...

**Comment by jeannotlanglois** [comment]
Hello @wdoekes + @rkday :  
This is a reminder not to forget to merge this pull request to complete the SIPP-RTPCHECK feature (and so that SIPP-3.7 release can proceed).

Happy Holidays!

**Pull request closed without merging**
