### PR TITLE
Build system cleanup

### PR DESCRIPTION
**Pull request by Lekensteyn**
This PR:
- removes auto-generated files from the repository (#112),
- generates the manual page as part of the build process (for up-to-date manual pages),
- updates README and build.sh to reflect these changes.

See the individual commits for details. Let me know what you think of it!

### CODE REVIEW

**Comment by lemenkov** [comment]
+1 from me

**Comment by rkday** [comment]
Yes, I'm happy to merge this - consensus on #112 seems to be in favour of removing these. I might kick off a 3.5.0 release soon - 3.4.1 was a while ago, and after this change I'd like to go through the process of generating a "make dist" tarball and uploading it to Github.

**Comment by kvishnivetsky** [comment]
+1 less garbage -> more order

**Comment by Lekensteyn** [comment]
This PR was already closed :-)

A follow-up PR is #121 which is nice if you want a working `make dist` target.

**Pull request merged**
